# You can use this file to easily send requests to your API.
# Prerequisite: humao.rest-client Vscode plugin (already present on codespace)
# High-level overview of REST API concepts used here: https://www.packtpub.com/en-us/learning/how-to-tutorials/what-are-rest-verbs-and-status-codes-tutorial


### Viewing Movie endpoint 
GET http://localhost:8080/api/movies/69b574dfc77f70080e866acb/watching/69b57496c77f70080e866ac9

### Recommended films for a specified user
GET http://localhost:8080/api/movies/recommended/69b574dfc77f70080e866acb

### Get all users
GET http://localhost:8080/api/users

### Get all movies
GET http://localhost:8080/api/movies

### Get all genres
GET http://localhost:8080/api/genres

### Get all subscriptions
GET http://localhost:8080/api/subscriptions

### Get all availabilities
GET http://localhost:8080/api/availabilities

### Create a new user (run this to populate variables for other requests)
# @name createUser
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "name": "Jean Valjean",
    "email": "prisoner24601@france.fr"
}

### Create a new genre
# @name createGenre
POST http://localhost:8080/api/genres
Content-Type: application/json

{
    "name": "Horror"
}

### Create a new genre
# @name createGenre2
POST http://localhost:8080/api/genres
Content-Type: application/json

{
    "name": "Comedy"
}

### Create a new movie
# @name createMovie
POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title": "Jaws",
    "description":"Pioneering horror film",
    "genreId": "{{createGenre.response.body.id}}", 
    "releaseDate":"08.03.2026",
    "duration":3000,
    "thumbnailUrl":"https://google.com",
    "videoUrl":"https://google.com"
}

### Create a new subscription
# @name createSubscription
POST http://localhost:8080/api/subscriptions
Content-Type: application/json

{
    "name": "30 day trial",
    "userId": "{{createUser.response.body.id}}",
    "price": 0.0,
    "duration": 3000,
    "end_date": "31.03.2026"
}

### Create a new subscription
# @name createAvailability
POST http://localhost:8080/api/availabilities
Content-Type: application/json

{
    "movieId": "69b57496c77f70080e866ac9",
    "subscriptionId": "69b57904b3378a0940b998e6",
    "availableUntil_date": "2026-05-31"
}

### Get user by ID (uses ID from createUser response)
GET http://localhost:8080/api/users/{{createUser.response.body.id}}

### Get user by email (uses email from createUser response)
GET http://localhost:8080/api/users/by-email?email={{createUser.response.body.email}}

### Update user name (PUT)
PUT http://localhost:8080/api/users/{{createUser.response.body.id}}
Content-Type: application/json

{
    "name": "Monsieur Madeleine"
}

### Update movie (PUT)
PUT http://localhost:8080/api/movies/69ae80c30561294eb59ed250
Content-Type: application/json

{
    "title": "Lord of the Rings the fellowship of the ring",
    "description":"Pioneering adventure film",
    "genreId":"0",
    "releaseDate":"05.03.1999",
    "duration":3000,
    "thumbnailUrl":"https://google.com",
    "videoUrl":"https://google.com"
}

### Update genre (PUT)
PUT http://localhost:8080/api/genres/{{createGenre2.response.body.id}}
Content-Type: application/json

{
    "name": "Family"
}

### Update subscription (PUT)
PUT http://localhost:8080/api/subscriptions/{{createSubscription.response.body.id}}
Content-Type: application/json

{
    "name": "10 day trial",
    "userId": "{{createUser.response.body.id}}",
    "price": 0.0,
    "duration": 1000,
    "end_date": "11.03.2026"
}

### Renew Subscription (PUT)
PATCH http://localhost:8080/api/subscriptions/subscribe/69b574dfc77f70080e866acb
Content-Type: application/json

{
    "userId":"69b574dfc77f70080e866acb"
}

### Renew Subscription (PUT)
PATCH http://localhost:8080/api/subscriptions/subscribe/69b574dfc77f70080e866acb
Content-Type: application/json

{
    "userId":"69b574dfc77f70080e866acb",
    "name":"20 day subscription trial",
    "duration":20,
    "price": 5000,
    "end_date":"2026-03-15"
}


### Change user name (PATCH)
PATCH http://localhost:8080/api/users/{{createUser.response.body.id}}/name
Content-Type: application/json

{
    "name": "Monsieur le Maire"
}

### Delete user
DELETE http://localhost:8080/api/users/{{createUser.response.body.id}}

### Delete movie
DELETE http://localhost:8080/api/movies/{{createMovie.response.body.id}}

### Delete genre
DELETE http://localhost:8080/api/genres/{{createGenre.response.body.id}}

### Delete subscription
DELETE http://localhost:8080/api/subscriptions/{{createSubscription.response.body.id}}


