server.port=8080
spring.application.name=prod-eng-service
mongodb.connection.url=${MONGODB_CONECTION_URL:mongodb://root:example@localhost:27017}
spring.data.mongodb.auto-index-creation=true

management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
management.endpoints.web.exposure.include=prometheus
