package ro.unibuc.prodeng.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import ro.unibuc.prodeng.model.UserEntity;
import ro.unibuc.prodeng.model.AvailabilityEntity;
import ro.unibuc.prodeng.model.MovieEntity;
import ro.unibuc.prodeng.repository.AvailabilityRepository;
import ro.unibuc.prodeng.repository.MovieRepository;
import ro.unibuc.prodeng.request.CreateUserRequest;
import ro.unibuc.prodeng.request.CreateMovieRequest;
import ro.unibuc.prodeng.request.CreateAvailabilityRequest;
import ro.unibuc.prodeng.response.UserResponse;
import ro.unibuc.prodeng.response.AvailabilityResponse;
import ro.unibuc.prodeng.response.MovieResponse;
import ro.unibuc.prodeng.exception.EntityNotFoundException;
import ro.unibuc.prodeng.request.EditMovieRequest;
import ro.unibuc.prodeng.request.EditAvailabilityRequest;

@Service
public class AvailabilityService {

    @Autowired
    private AvailabilityRepository availabilityRepository;

    public List<AvailabilityResponse> getAllAvailabilities() throws EntityNotFoundException {
        return availabilityRepository.findAll().stream().map(this::toResponse).toList();
    }
    
    public AvailabilityResponse createAvailability(CreateAvailabilityRequest request) {

        AvailabilityEntity availability = new AvailabilityEntity(
                null, // ID will be generated by the repository
                request.movieId(),
                request.subscriptionId(),
                request.availableUntil_date()
        );
        AvailabilityEntity saved = availabilityRepository.save(availability);
        return toResponse(saved);
    }
    public AvailabilityResponse getAvailabilityById(String id) throws EntityNotFoundException {
        AvailabilityEntity availability = availabilityRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        return toResponse(availability);
    }

    public AvailabilityEntity getAvailabilityEntityById(String id) throws EntityNotFoundException {
        return availabilityRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
    }

    public AvailabilityResponse editAvailability(String id, EditAvailabilityRequest newAvailability) throws EntityNotFoundException {
        AvailabilityEntity existing = availabilityRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        AvailabilityEntity updated = new AvailabilityEntity(existing.id(),newAvailability.movieId(),newAvailability.subscriptionId(),newAvailability.availableUntil_date());
        AvailabilityEntity saved = availabilityRepository.save(updated);
        return toResponse(saved);
    }
    
    public void deleteAvailability(String id) throws EntityNotFoundException {
        if (!availabilityRepository.existsById(id)) {
            throw new EntityNotFoundException(id);
        }
        availabilityRepository.deleteById(id);
    }

    private AvailabilityResponse toResponse(AvailabilityEntity availability) {
        return new AvailabilityResponse(
            availability.id(),
            availability.movieId(),
            availability.subscriptionId(),
            availability.availableUntil_date()
        );
    }
}
