package ro.unibuc.prodeng.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import ro.unibuc.prodeng.model.UserEntity;
import ro.unibuc.prodeng.model.GenreEntity;
import ro.unibuc.prodeng.model.MovieEntity;
import ro.unibuc.prodeng.repository.GenreRepository;
import ro.unibuc.prodeng.repository.MovieRepository;
import ro.unibuc.prodeng.request.CreateUserRequest;
import ro.unibuc.prodeng.request.CreateMovieRequest;
import ro.unibuc.prodeng.request.CreateGenreRequest;
import ro.unibuc.prodeng.response.UserResponse;
import ro.unibuc.prodeng.response.GenreResponse;
import ro.unibuc.prodeng.response.MovieResponse;
import ro.unibuc.prodeng.exception.EntityNotFoundException;
import ro.unibuc.prodeng.request.EditMovieRequest;
import ro.unibuc.prodeng.request.EditGenreRequest;

@Service
public class GenreService {

    @Autowired
    private GenreRepository genreRepository;

    public List<GenreResponse> getAllGenres() throws EntityNotFoundException {
        return genreRepository.findAll().stream().map(this::toResponse).toList();
    }
    
    public GenreResponse createGenre(CreateGenreRequest request) {

        GenreEntity genre = new GenreEntity(
                null, // ID will be generated by the repository
                request.name()
        );
        GenreEntity saved = genreRepository.save(genre);
        return toResponse(saved);
    }
    public GenreResponse getGenreById(String id) throws EntityNotFoundException {
        GenreEntity genre = genreRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        return toResponse(genre);
    }

    public GenreEntity getGenreEntityById(String id) throws EntityNotFoundException {
        return genreRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
    }

    public GenreResponse editGenre(String id, EditGenreRequest newGenre) throws EntityNotFoundException {
        GenreEntity existing = genreRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        GenreEntity updated = new GenreEntity(existing.id(),newGenre.name());
        GenreEntity saved = genreRepository.save(updated);
        return toResponse(saved);
    }
    
    public void deleteGenre(String id) throws EntityNotFoundException {
        if (!genreRepository.existsById(id)) {
            throw new EntityNotFoundException(id);
        }
        genreRepository.deleteById(id);
    }

    private GenreResponse toResponse(GenreEntity genre) {
        return new GenreResponse(
            genre.id(),
            genre.name()
        );
    }
}
