package ro.unibuc.prodeng.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import ro.unibuc.prodeng.model.UserEntity;
import ro.unibuc.prodeng.model.MovieEntity;
import ro.unibuc.prodeng.repository.MovieRepository;
import ro.unibuc.prodeng.request.CreateUserRequest;
import ro.unibuc.prodeng.request.CreateMovieRequest;
import ro.unibuc.prodeng.response.UserResponse;
import ro.unibuc.prodeng.response.MovieResponse;
import ro.unibuc.prodeng.exception.EntityNotFoundException;
import ro.unibuc.prodeng.request.EditMovieRequest;

@Service
public class MovieService {

    @Autowired
    private MovieRepository movieRepository;

    public List<MovieResponse> getAllMovies() throws EntityNotFoundException {
        return movieRepository.findAll().stream().map(this::toResponse).toList();
    }
    
    public MovieResponse createMovie(CreateMovieRequest request) {

        MovieEntity movie = new MovieEntity(
                null, // ID will be generated by the repository
                request.title(),
                request.description(),
                request.genreId(),
                request.releaseDate(),
                request.duration(),
                0,
                request.thumbnailUrl(),
                request.videoUrl()
        );
        MovieEntity saved = movieRepository.save(movie);
        return toResponse(saved);
    }
    public MovieResponse getMovieById(String id) throws EntityNotFoundException {
        MovieEntity movie = movieRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        return toResponse(movie);
    }

    public MovieEntity getMovieEntityById(String id) throws EntityNotFoundException {
        return movieRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
    }

    public MovieResponse editMovie(String id, EditMovieRequest newMovie) throws EntityNotFoundException {
        MovieEntity existing = movieRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        MovieEntity updated = new MovieEntity(existing.id(),newMovie.title(),newMovie.description(),newMovie.genreId(),newMovie.releaseDate(),newMovie.duration(),newMovie.totalViews(),newMovie.thumbnailUrl(),newMovie.videoUrl());
        MovieEntity saved = movieRepository.save(updated);
        return toResponse(saved);
    }
    
    public void deleteMovie(String id) throws EntityNotFoundException {
        if (!movieRepository.existsById(id)) {
            throw new EntityNotFoundException(id);
        }
        movieRepository.deleteById(id);
    }

    private MovieResponse toResponse(MovieEntity movie) {
        return new MovieResponse(
            movie.id(),
            movie.title(),
            movie.description(),
            movie.genreId(),
            movie.releaseDate(),
            movie.duration(),
            movie.totalViews(),
            movie.thumbnailUrl(),
            movie.videoUrl()
        );
    }
}
