package ro.unibuc.prodeng.service;

import java.time.LocalDate;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import ro.unibuc.prodeng.model.MovieEntity;
import ro.unibuc.prodeng.model.AvailabilityEntity;
import ro.unibuc.prodeng.model.SubscriptionEntity;
import ro.unibuc.prodeng.repository.AvailabilityRepository;
import ro.unibuc.prodeng.repository.GenreRepository;
import ro.unibuc.prodeng.repository.MovieRepository;
import ro.unibuc.prodeng.repository.RatingRepository;
import ro.unibuc.prodeng.repository.SubscriptionRepository;
import ro.unibuc.prodeng.request.CreateMovieRequest;
import ro.unibuc.prodeng.response.MovieResponse;
import ro.unibuc.prodeng.response.MovieWithRatingResponse;
import ro.unibuc.prodeng.exception.EntityNotFoundException;
import ro.unibuc.prodeng.request.EditMovieRequest;

@Service
public class MovieService {

    @Autowired
    private MovieRepository movieRepository;

    @Autowired
    private SubscriptionRepository subscriptionRepository;

    @Autowired
    private AvailabilityRepository availabilityRepository;

    @Autowired
    private GenreRepository genreRepository;

    @Autowired
    private RatingRepository ratingRepository;

    public List<MovieResponse> getAllMovies() throws EntityNotFoundException {
        return movieRepository.findAll().stream().map(this::toResponse).toList();
    }
    
    public MovieResponse createMovie(CreateMovieRequest request) {

        MovieEntity movie = new MovieEntity(
                null, // ID will be generated by the repository
                request.title(),
                request.description(),
                request.genreId(),
                request.releaseDate(),
                request.duration(),
                0,
                request.thumbnailUrl(),
                request.videoUrl()
        );
        MovieEntity saved = movieRepository.save(movie);
        return toResponse(saved);
    }
    public MovieResponse getMovieById(String id) throws EntityNotFoundException {
        MovieEntity movie = movieRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        return toResponse(movie);
    }

    public MovieEntity getMovieEntityById(String id) throws EntityNotFoundException {
        return movieRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
    }

    public MovieResponse editMovie(String id, EditMovieRequest newMovie) throws EntityNotFoundException {
        MovieEntity existing = movieRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        MovieEntity updated = new MovieEntity(existing.id(),newMovie.title(),newMovie.description(),newMovie.genreId(),newMovie.releaseDate(),newMovie.duration(),newMovie.totalViews(),newMovie.thumbnailUrl(),newMovie.videoUrl());
        MovieEntity saved = movieRepository.save(updated);
        return toResponse(saved);
    }
    
    public void deleteMovie(String id) throws EntityNotFoundException {
        if (!movieRepository.existsById(id)) {
            throw new EntityNotFoundException(id);
        }
        movieRepository.deleteById(id);
    }

    public MovieResponse watchMovie(String id, String uid) throws EntityNotFoundException{
        SubscriptionEntity subscription = subscriptionRepository
        .findByUserId(uid).orElseThrow(() -> new EntityNotFoundException(uid));
        AvailabilityEntity availability = availabilityRepository
        .findByMovieIdAndSubscriptionId(id, subscription.id()).orElseThrow(() -> new EntityNotFoundException(id));
        
        LocalDate Today=LocalDate.now();
            if(Today.isAfter(LocalDate.parse(subscription.end_date())) || Today.isAfter(LocalDate.parse(availability.availableUntil_date())))
                throw new IllegalStateException("Expired!!");
        MovieEntity movieToBeWatched=movieRepository.findById(id).orElseThrow(() -> new EntityNotFoundException(id));
        return toResponse(movieToBeWatched);
    }
    private MovieResponse toResponse(MovieEntity movie) {
        return new MovieResponse(
            movie.id(),
            movie.title(),
            movie.description(),
            movie.genreId(),
            movie.releaseDate(),
            movie.duration(),
            movie.totalViews(),
            movie.thumbnailUrl(),
            movie.videoUrl()
        );
    }


    public double getAverageRating(String movieId) {

        Double avg = ratingRepository.getAverageRatingForMovie(movieId);

        if (avg == null) {
            return 0;
        }

        return avg;
    }


    public List<MovieWithRatingResponse> getMoviesSortedByRating() {

        List<MovieEntity> movies = movieRepository.findAll();

        return movies.stream()
                .map(movie -> new MovieWithRatingResponse(
                        movie.id(),
                        movie.title(),
                        movie.description(),
                        movie.totalViews(),
                        getAverageRating(movie.id())
                ))
                .sorted((a, b) -> Double.compare(b.averageRating(), a.averageRating()))
                .toList();
    }


    public List<MovieResponse> getMoviesSortedByViews() {
        return movieRepository.findAllByOrderByTotalViewsDesc()
                .stream()
                .map(this::toResponse)
                .toList();
    }


    public List<MovieResponse> searchMovies(String query) {

        List<MovieEntity> movies = movieRepository.searchByText(query);

        return movies.stream()
                .map(this::toResponse)
                .toList();
    }


}
