package ro.unibuc.prodeng.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import ro.unibuc.prodeng.model.UserEntity;
import ro.unibuc.prodeng.model.SubscriptionEntity;
import ro.unibuc.prodeng.repository.SubscriptionRepository;
import ro.unibuc.prodeng.request.CreateUserRequest;
import ro.unibuc.prodeng.request.CreateSubscriptionRequest;
import ro.unibuc.prodeng.response.UserResponse;
import ro.unibuc.prodeng.response.SubscriptionResponse;
import ro.unibuc.prodeng.exception.EntityNotFoundException;
import ro.unibuc.prodeng.request.EditSubscriptionRequest;

@Service
public class SubscriptionService {

    @Autowired
    private SubscriptionRepository subscriptionRepository;

    public List<SubscriptionResponse> getAllSubscriptions() throws EntityNotFoundException {
        return subscriptionRepository.findAll().stream().map(this::toResponse).toList();
    }
    
    public SubscriptionResponse createSubscription(CreateSubscriptionRequest request) {

        SubscriptionEntity subscription = new SubscriptionEntity(
                null, // ID will be generated by the repository
                request.userId(),
                request.name(),
                request.price(),
                request.duration(),
                request.end_date()
        );
        SubscriptionEntity saved = subscriptionRepository.save(subscription);
        return toResponse(saved);
    }
    public SubscriptionResponse getSubscriptionById(String id) throws EntityNotFoundException {
        SubscriptionEntity subscription = subscriptionRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        return toResponse(subscription);
    }

    public SubscriptionEntity getSubscriptionEntityById(String id) throws EntityNotFoundException {
        return subscriptionRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
    }

    public SubscriptionResponse editSubscription(String id, EditSubscriptionRequest newSubscription) throws EntityNotFoundException {
        SubscriptionEntity existing = subscriptionRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        SubscriptionEntity updated = new SubscriptionEntity(existing.id(),newSubscription.userId(),newSubscription.name(),newSubscription.price(),newSubscription.duration(),newSubscription.end_date());
        SubscriptionEntity saved = subscriptionRepository.save(updated);
        return toResponse(saved);
    }
    
    public void deleteSubscription(String id) throws EntityNotFoundException {
        if (!subscriptionRepository.existsById(id)) {
            throw new EntityNotFoundException(id);
        }
        subscriptionRepository.deleteById(id);
    }

    private SubscriptionResponse toResponse(SubscriptionEntity subscription) {
        return new SubscriptionResponse(
            subscription.id(),
            subscription.userId(),
            subscription.name(),
            subscription.price(),
            subscription.duration(),
            subscription.end_date()
        );
    }
}
